version: '3.7'

services:
  pizzapoll-db:
    image: mongo:4.2.3
    container_name: pizzapoll-db

    ports:
      - 27017:27017

    volumes:
      - pizzapoll-db-data:/data/db

#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  pizzapoll-db-data: